// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Format = require("bs-platform/lib/js/format.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function bal(s) {
  if (Caml_string.get(s, 0) === /* "[" */91) {
    var rest = s.slice(1);
    var inner = bal(rest);
    return /* Pair */[/* Some */[inner]];
  } else if (Caml_string.get(s, 0) === /* "]" */93) {
    return /* Pair */[/* None */0];
  } else {
    return Js_exn.raiseError("Unrecognized character.");
  }
}

function stringOfPair(pair) {
  var match = pair[0];
  if (match) {
    return Curry._1(Format.sprintf(/* Format */[
                    /* Char_literal */Block.__(12, [
                        /* "(" */40,
                        /* String */Block.__(2, [
                            /* No_padding */0,
                            /* Char_literal */Block.__(12, [
                                /* ")" */41,
                                /* End_of_format */0
                              ])
                          ])
                      ]),
                    "(%s)"
                  ]), stringOfPair(match[0]));
  } else {
    return "";
  }
}

console.log(stringOfPair(bal("[[[]]]")));

exports.bal = bal;
exports.stringOfPair = stringOfPair;
/*  Not a pure module */
