// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Format = require("bs-platform/lib/js/format.js");
var Stream = require("bs-platform/lib/js/stream.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function seq(parser1, parser2, charStream) {
  console.log("seq called.");
  var match = Curry._1(parser1, charStream);
  if (match[0] >= 781116926) {
    return /* `Fail */[
            781116926,
            "Parser 1 failed with message: " + match[1]
          ];
  } else {
    var match$1 = match[1];
    var match$2 = Curry._1(parser2, match$1[1]);
    if (match$2[0] >= 781116926) {
      return /* `Fail */[
              781116926,
              "Parser 1 succeeded, but parser 2 failed with message: " + match$2[1]
            ];
    } else {
      var match$3 = match$2[1];
      return /* `Success */[
              94326179,
              /* tuple */[
                /* `List */[
                  848054398,
                  /* :: */[
                    match$1[0],
                    /* :: */[
                      match$3[0],
                      /* [] */0
                    ]
                  ]
                ],
                match$3[1]
              ]
            ];
    }
  }
}

function nextOpt(stream) {
  try {
    return /* Some */[Stream.next(stream)];
  }
  catch (exn){
    if (exn === Stream.Failure) {
      return /* None */0;
    } else {
      throw exn;
    }
  }
}

function stringOfStringList(lst) {
  return $$Array.of_list(lst).join(", ");
}

function stringOfCharList(lst) {
  var lst$1 = List.map(Char.escaped, lst);
  return $$Array.of_list(lst$1).join(", ");
}

function alt(parserStream, charStream) {
  while(true) {
    console.log("alt called.");
    var lst = List.map(Char.escaped, charStream);
    console.log($$Array.of_list(lst).join(", "));
    var match = nextOpt(parserStream);
    if (match) {
      var success = Curry._1(match[0], charStream);
      if (success[0] >= 781116926) {
        continue ;
        
      } else {
        return success;
      }
    } else {
      return /* `Fail */[
              781116926,
              "None of the parsers matched"
            ];
    }
  };
}

var Combinator = /* module */[
  /* seq */seq,
  /* nextOpt */nextOpt,
  /* stringOfStringList */stringOfStringList,
  /* stringOfCharList */stringOfCharList,
  /* alt */alt
];

function stringOfStringList$1(lst) {
  return $$Array.of_list(lst).join(", ");
}

function stringOfCharList$1(lst) {
  var lst$1 = List.map(Char.escaped, lst);
  return $$Array.of_list(lst$1).join(", ");
}

function stringOfValue(v) {
  if (typeof v === "number") {
    return "I don't know how to stringify this!";
  } else {
    var variant = v[0];
    if (variant !== -677568250) {
      if (variant !== -319464051) {
        if (variant !== 848054398) {
          return "I don't know how to stringify this!";
        } else {
          var lst = List.map(stringOfValue, v[1]);
          return "[" + ($$Array.of_list(lst).join(", ") + "]");
        }
      } else {
        return Pervasives.string_of_int(v[1]);
      }
    } else {
      return Char.escaped(v[1]);
    }
  }
}

function letter(stream) {
  console.log("letter called.");
  if (stream) {
    var c = stream[0];
    var match = +(65 <= c && c <= 90 || 97 <= c && c <= 122);
    if (match !== 0) {
      return /* `Success */[
              94326179,
              /* tuple */[
                /* `Letter */[
                  -677568250,
                  c
                ],
                stream[1]
              ]
            ];
    } else {
      return /* `Fail */[
              781116926,
              "Not a letter."
            ];
    }
  } else {
    return /* `Fail */[
            781116926,
            "Stream is empty"
          ];
  }
}

function digit(stream) {
  console.log("digit called.");
  if (stream) {
    var c = stream[0];
    var match = +(48 <= c && c <= 57);
    if (match !== 0) {
      return /* `Success */[
              94326179,
              /* tuple */[
                /* `Digit */[
                  -319464051,
                  Caml_format.caml_int_of_string(Char.escaped(c))
                ],
                stream[1]
              ]
            ];
    } else {
      return /* `Fail */[
              781116926,
              "Not a digit."
            ];
    }
  } else {
    return /* `Fail */[
            781116926,
            "Stream is empty"
          ];
  }
}

function p(param) {
  return seq(letter, digit, param);
}

var partial_arg = Stream.of_list(/* :: */[
      letter,
      /* :: */[
        digit,
        /* [] */0
      ]
    ]);

function q(param) {
  return alt(partial_arg, param);
}

function r(param) {
  return seq(p, q, param);
}

var match = r(/* :: */[
      /* "a" */97,
      /* :: */[
        /* "0" */48,
        /* :: */[
          /* "b" */98,
          /* :: */[
            /* "1" */49,
            /* [] */0
          ]
        ]
      ]
    ]);

var tmp;

if (match[0] >= 781116926) {
  tmp = Curry._1(Format.sprintf(/* Format */[
            /* String_literal */Block.__(11, [
                "fail!\n",
                /* String */Block.__(2, [
                    /* No_padding */0,
                    /* End_of_format */0
                  ])
              ]),
            "fail!\n%s"
          ]), match[1]);
} else {
  var match$1 = match[1];
  var lst = List.map(Char.escaped, match$1[1]);
  tmp = Curry._2(Format.sprintf(/* Format */[
            /* String_literal */Block.__(11, [
                "success!\nvalue: ",
                /* String */Block.__(2, [
                    /* No_padding */0,
                    /* String_literal */Block.__(11, [
                        ", rest: ",
                        /* String */Block.__(2, [
                            /* No_padding */0,
                            /* End_of_format */0
                          ])
                      ])
                  ])
              ]),
            "success!\nvalue: %s, rest: %s"
          ]), stringOfValue(match$1[0]), $$Array.of_list(lst).join(", "));
}

console.log(tmp);

exports.Combinator = Combinator;
exports.stringOfStringList = stringOfStringList$1;
exports.stringOfCharList = stringOfCharList$1;
exports.stringOfValue = stringOfValue;
exports.letter = letter;
exports.digit = digit;
exports.p = p;
exports.q = q;
exports.r = r;
/* partial_arg Not a pure module */
