// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var Revamp = require("@glennsl/bs-revamp/lib/js/src/Revamp.js");

function regExp(re, string) {
  var match = Revamp.find(re.source, /* None */0, string);
  if (match) {
    var match_ = match[0];
    var remainder = string.slice(match_.length);
    return /* `Success */[
            94326179,
            /* tuple */[
              /* `String */[
                -976970511,
                match_
              ],
              remainder
            ]
          ];
  } else {
    return /* `Fail */[
            781116926,
            "Match not found."
          ];
  }
}

function $$char(c) {
  var partial_arg = new RegExp("^" + Char.escaped(c));
  return (function (param) {
      return regExp(partial_arg, param);
    });
}

function letter(s) {
  return regExp((/^[A-Za-z]/), s);
}

function letters(s) {
  return regExp((/^[A-Za-z]+/), s);
}

function digit(s) {
  return regExp((/^[0-9]/), s);
}

function digits(s) {
  return regExp((/^[0-9]+/), s);
}

function maybeWhitespace(s) {
  return regExp((/^\s*/), s);
}

exports.regExp = regExp;
exports.$$char = $$char;
exports.letter = letter;
exports.letters = letters;
exports.digit = digit;
exports.digits = digits;
exports.maybeWhitespace = maybeWhitespace;
/* No side effect */
