// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Node$ReasonParse = require("./node.js");
var Combs$ReasonParse = require("./combs.js");
var Regex$ReasonParse = require("./regex.js");

function q(param) {
  return Combs$ReasonParse.map(Regex$ReasonParse.intMapper, Regex$ReasonParse.digits, param);
}

var partial_arg_001 = /* :: */[
  Regex$ReasonParse.letters,
  /* :: */[
    q,
    /* :: */[
      Regex$ReasonParse.letters,
      /* [] */0
    ]
  ]
];

var partial_arg = /* :: */[
  q,
  partial_arg_001
];

function pq(param) {
  return Combs$ReasonParse.seq(partial_arg, param);
}

var n = pq("456ABCdef123abc***");

var s;

s = n.tag ? n[0] : Node$ReasonParse.stringOfNode(n[0]);

console.log(s);

var p = Regex$ReasonParse.letters;

exports.p = p;
exports.q = q;
exports.pq = pq;
exports.n = n;
exports.s = s;
/* n Not a pure module */
